# Generated by Django 3.1.1 on 2020-10-17 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasureHunt',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('team_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('treasure_hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clues.treasurehunt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clues',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treasureHunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clues.treasurehunt')),
            ],
        ),
        migrations.CreateModel(
            name='AttributedClues',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clues.clues')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clues.participant')),
            ],
        ),
    ]
